type TMetadata = {
	'url': string,
	'canonical': string,
	'title': string,
	'image': string,
	'author': string,
	'description': string,
	'keywords': string,
	'source': string,
	'price': string,
	'priceCurrency': string,
	'availability': string,
	'robots': string,
	'og:url': string,
	'og:locale': string,
	'og:locale:alternate': string,
	'og:title': string,
	'og:type': string,
	'og:description': string,
	'og:determiner': string,
	'og:site_name': string,
	'og:image': string,
	'og:image:secure_url': string,
	'og:image:type': string,
	'og:image:width': string,
	'og:image:height': string,
	'twitter:title': string,
	'twitter:image': string,
	'twitter:image:alt': string,
	'twitter:card': string,
	'twitter:site': string,
	'twitter:site:id': string,
	'twitter:account_id': string,
	'twitter:creator': string,
	'twitter:creator:id': string,
	'twitter:player': string,
	'twitter:player:width': string,
	'twitter:player:height': string,
	'twitter:player:stream': string,
	'viewport': string,
	'msapplication-TileColor': string,
	'theme-color': string,
	'application-name': string,
	'apple-mobile-web-app-title': string,
	'apple-mobile-web-app-capable': string,
	'apple-mobile-web-app-status-bar-style': string,
	'format-detection': string,
	'mobile-web-app-capable': string,
	'msapplication-config': string,
	'msapplication-tap-highlight': string,
	'googlebot': string,
	'og:image:alt': string,
	'next-head-count': string,
	'git-url': string,
}

type TGithubReleases = {
	'url': string, 
	'assets_url': string, 
	'upload_url': string, 
	'html_url': string,
	'id': number,
	'node_id': string,
	'tag_name': string,
	'target_commitish': string,
	'name': string,
	'draft': boolean,
	'prerelease': boolean,
	'created_at': string,
	'published_at': string,
	'tarball_url': string,
	'zipball_url': string,
	'body': string,
}

type TOverwrite = Partial<TMetadata>

export type {TMetadata, TGithubReleases, TOverwrite};